from pathlib import Path
ROOT_FOLDER = Path(__file__).parent
IMAGES_FOLDER = ROOT_FOLDER / 'images'

BIG_FONT = 40
MEDIUM_FONT = 28
SMALL_FONT = 16

MINIMUM_WIDTH = 200
PRIMARY_COLOR = '#1e81b0'
DARKER_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'

